services:
  wik-wms-api:
    image: wik/wms-api
    container_name: wik-wms-api
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev-persi-qas
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api/logs:/app/log
      - ./api/sap:/app/sap
  wik-wms-ws:
    image: cr.io/wik/wms-ws
    container_name: wik-wms-ws
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ws/logs:/app/log